import { Bebas_Neue, Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import PrivateRoute from "@/lib/PrivateRoute";
import Script from "next/script";

const bebas = Bebas_Neue({
  variable: "--font-bebas",
  subsets: ["latin"],
  weight: "400", // Add this line

});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Add this line
});


export const metadata = {
  title: "RCL Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      {/* Google tag (gtag.js) */}
      <Script async src="https://www.googletagmanager.com/gtag/js?id=G-9BRFC5JVKB" />
      <Script>
        {`window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-9BRFC5JVKB');`}
      </Script>
      <div className={`${bebas.variable} ${poppins.variable} antialiased dark`}>
        {children}
        <Toaster richColors  />
      </div>
    </>
  );
}
